//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DD_Footwear.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoIncrementShoeID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string autoIncrementShoeID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoIncrementShoeID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> autoIncrementShoeIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addShoe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addShoe(string id, string name, string price, string description, string stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addShoe", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addShoeAsync(string id, string name, string price, string description, string stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateShoe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool updateShoe(string id, string name, string price, string description, string stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateShoe", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> updateShoeAsync(string id, string name, string price, string description, string stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteShoe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet deleteShoe(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteShoe", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> deleteShoeAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchShoeName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchShoeName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchShoeName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchShoeNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addOrder(string name, string sname, string mobile, string qtn, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addOrderAsync(string name, string sname, string mobile, string qtn, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPreOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addPreOrder(string name, string sname, string mobile, string qtn, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPreOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addPreOrderAsync(string name, string sname, string mobile, string qtn, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchSupp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchSupp(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchSupp", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchSuppAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : DD_Footwear.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<DD_Footwear.ServiceReference1.WebServiceSoap>, DD_Footwear.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string autoIncrementShoeID() {
            return base.Channel.autoIncrementShoeID();
        }
        
        public System.Threading.Tasks.Task<string> autoIncrementShoeIDAsync() {
            return base.Channel.autoIncrementShoeIDAsync();
        }
        
        public string addShoe(string id, string name, string price, string description, string stock) {
            return base.Channel.addShoe(id, name, price, description, stock);
        }
        
        public System.Threading.Tasks.Task<string> addShoeAsync(string id, string name, string price, string description, string stock) {
            return base.Channel.addShoeAsync(id, name, price, description, stock);
        }
        
        public bool updateShoe(string id, string name, string price, string description, string stock) {
            return base.Channel.updateShoe(id, name, price, description, stock);
        }
        
        public System.Threading.Tasks.Task<bool> updateShoeAsync(string id, string name, string price, string description, string stock) {
            return base.Channel.updateShoeAsync(id, name, price, description, stock);
        }
        
        public System.Data.DataSet deleteShoe(string name) {
            return base.Channel.deleteShoe(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> deleteShoeAsync(string name) {
            return base.Channel.deleteShoeAsync(name);
        }
        
        public System.Data.DataSet searchShoeName(string name) {
            return base.Channel.searchShoeName(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchShoeNameAsync(string name) {
            return base.Channel.searchShoeNameAsync(name);
        }
        
        public string addOrder(string name, string sname, string mobile, string qtn, string address) {
            return base.Channel.addOrder(name, sname, mobile, qtn, address);
        }
        
        public System.Threading.Tasks.Task<string> addOrderAsync(string name, string sname, string mobile, string qtn, string address) {
            return base.Channel.addOrderAsync(name, sname, mobile, qtn, address);
        }
        
        public string addPreOrder(string name, string sname, string mobile, string qtn, string address) {
            return base.Channel.addPreOrder(name, sname, mobile, qtn, address);
        }
        
        public System.Threading.Tasks.Task<string> addPreOrderAsync(string name, string sname, string mobile, string qtn, string address) {
            return base.Channel.addPreOrderAsync(name, sname, mobile, qtn, address);
        }
        
        public System.Data.DataSet searchSupp(string name) {
            return base.Channel.searchSupp(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchSuppAsync(string name) {
            return base.Channel.searchSuppAsync(name);
        }
    }
}
